---
# Add this as an override to submit connectors.
# example: docker compose -f docker-compose.yml -f kafka-connect/submit-connectors.yml up -d

services:
  submit-connectors:
    image: confluentinc/cp-server-connect-base:latest
    hostname: submit-connectors
    container_name: submit-connectors
    depends_on:
      connect:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      splunk:
        condition: service_healthy
    volumes:
      - ./scripts/submit-connector.sh:/usr/bin/submit-connector.sh
      - ./kafka-connect/connectors:/connectors
    command:
      - bash
      - -c
      - |
        for connector in /connectors/*.json; do submit-connector.sh $${connector} connect; done
