github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: false

tasks:
  - name: download pcap
    init: python3 scripts/get_pcap.py
  
  - name: download docker images
    init: docker-compose pull 

  - name: start services
    command: docker-compose up -d

ports:

### Graphical User Interface (GUI) Apps

  # Confluent Control Center
  - port: 9021
    onOpen: notify
    visibility: public

  # Confluent Sigma UI
  - port: 8080
    onOpen: notify
    visibility: public

  # Kibana UI
  - port: 5601
    onOpen: notify
    visibility: public

  # Splunk UI
  - port: 8000
    onOpen: notify
    visibility: public

### Backend Services

  # zookeeper
  - port: 2181
    onOpen: ignore
    
  # Confluent Server (Kafka broker)
  - port: 9092
    onOpen: ignore
    
  # Confluent Schema Registry
  - port: 8081
    onOpen: ignore

  # Confluent ksqlDB
  - port: 8088
    onOpen: ignore

  # Kafka Connect REST endpoint
  - port: 8083
    onOpen: ignore

  # Connect receives data from Splunk Universal Forwarder
  - port: 9997
    onOpen: ignore

  # Connect receives syslog data
  - port: 5140
    onOpen: ignore

  # Splunk HTTP Event Collector (HEC)
  - port: 8090
    onOpen: ignore

  # Splunk Universal Forwarder
  - port: 3333
    onOpen: ignore

  # Splunk Event Generator
  - port: 9500
    onOpen: ignore

  # Splunk Event Generator (Redis cache)
  - port: 6379
    onOpen: ignore

  # Confluent REST Proxy (unnecessary?)
  - port: 8082
    onOpen: ignore

  # ElasticSearch
  - port: 9200
    onOpen: ignore

  # ElasticSearch
  - port: 9300
    onOpen: ignore

  # Broker JMX metrics
  - port: 9101
    onOpen: ignore
