CREATE STREAM CISCO_ASA_FILTER_106023
WITH (KAFKA_TOPIC='CISCO_ASA_FILTER_106023', PARTITIONS=1, REPLICAS=1, VALUE_FORMAT='AVRO')
AS SELECT
    SPLUNK.event,
    SPLUNK.source,
    SPLUNK.sourcetype,
    SPLUNK.index
FROM SPLUNK SPLUNK
WHERE ((SPLUNK.sourcetype = 'cisco:asa') AND (NOT (SPLUNK.event LIKE '%ASA-4-106023%')))
EMIT CHANGES;
