CREATE STREAM MATCHED_DOMAINS_DNS
WITH (KAFKA_TOPIC='matched_dns', PARTITIONS=1, REPLICAS=1, VALUE_FORMAT='AVRO')
AS SELECT *
    FROM RICH_DNS INNER JOIN DOMAIN_WATCHLIST
    ON RICH_DNS."query" = DOMAIN_WATCHLIST.DOMAIN
EMIT CHANGES;
